import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import FirebaseInit from "./FirebaseInit";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FirebaseInit>{children}</FirebaseInit>
        <ToastContainer
            position="bottom-center"
            hideProgressBar
            pauseOnFocusLoss={false}
            pauseOnHover={false}
          />
      </body>
    </html>
  );
}
